version: '3.8'

services:
    app:
        build: .
        container_name: greenbook-app
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/greenbook?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - SPRING_DATASOURCE_USERNAME=greenbook
            - SPRING_DATASOURCE_PASSWORD=greenbook123
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_JPA_SHOW_SQL=false
            - GOOGLE_API_KEY=
        volumes:
            - greenbook-uploads:/app/uploads
        networks:
            - greenbook-network

    db:
        image: mysql:8.0
        container_name: greenbook-db
        restart: always
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=greenbook
            - MYSQL_USER=greenbook
            - MYSQL_PASSWORD=greenbook123
            - MYSQL_ROOT_PASSWORD=rootpassword
        volumes:
            - greenbook-mysql-data:/var/lib/mysql
            - ./src/main/resources/sql:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - greenbook-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: greenbook-phpmyadmin
        restart: always
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - greenbook-network

volumes:
    greenbook-mysql-data:
    greenbook-uploads:

networks:
    greenbook-network:
        driver: bridge
